spring:
  application.name: backend

  datasource:
    url: ''
    username: ''
    password: ''

  jpa.open-in-view: false

  liquibase:
    change-log: /db/changelog/db.changelog-master.xml

spotify:
  apiUrl: 'https://api.spotify.com/v1'
  oauth:
    baseUrl: 'https://accounts.spotify.com'
    authorizeUrl: '${spotify.oauth.baseUrl}/authorize'
    tokensUrl: '${spotify.oauth.baseUrl}/api/token'
    client:
      id: ''
      secret: ''

strava:
  apiUrl: 'https://www.strava.com/api/v3'
  oauth:
    authorizeUrl: 'https://www.strava.com/oauth/authorize'
    tokensUrl: '${strava.apiUrl}/oauth/token'
    client:
      id: ''
      secret: ''

application:
  url: http://localhost:8080
