spring:
  application.name: backend

  datasource:
    url: 'docker-compose'
    username: 'docker-compose'
    password: 'docker-compose'

  jpa.open-in-view: false

  liquibase:
    change-log: /db/changelog/db.changelog-master.xml

spotify:
  apiUrl: 'https://api.spotify.com/v1'
  oauth:
    baseUrl: 'https://accounts.spotify.com'
    authorizeUrl: '${spotify.oauth.baseUrl}/authorize'
    tokensUrl: '${spotify.oauth.baseUrl}/api/token'
    state: spotifystate
    client:
      id: ''
      secret: ''

strava:
  apiUrl: 'https://www.strava.com/api/v3'
  oauth:
    authorizeUrl: 'https://www.strava.com/oauth/authorize'
    tokensUrl: '${strava.apiUrl}/oauth/token'
    state: stravastate
    client:
      id: ''
      secret: ''

application:
  url: http://localhost:8080

jasypt:
  password: localhost
  jpaPassword: localhost
